AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: A simple Hello World Serverless project
Parameters:
    CodeUri:
        Type: String

Resources:
  lambda2:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: index.handler
      CodeUri: !Sub "${CodeUri}"
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /lambda2
            Method: get
      Environment:
        Variables:
          LAMBDA1: !ImportValue lambda1-LambdaFunction


